/**
 * Contiene la lista de campeones y sus regiones para
 * la lógica de misiones.
 * (v8.0) - Corregida para 3 columnas
 */
function getChampionDataList() {
  return [
    ["Aatrox", "Runeterra", "Shurima"],
    ["Ahri", "Ionia", ""],
    ["Akali", "Ionia", ""],
    ["Akshan", "Shurima", ""],
    ["Alistar", "Runeterra", ""],
    ["Amumu", "Shurima", ""],
    ["Anivia", "Freljord", ""],
    ["Annie", "Runeterra", ""],
    ["Aphelios", "Targon", ""],
    ["Ashe", "Freljord", ""],
    ["Aurelion Sol", "Targon", "Runeterra"],
    ["Azir", "Shurima", ""],
    ["Bard", "Runeterra", ""],
    ["Bel'Veth", "Void", ""],
    ["Blitzcrank", "Zaun", ""],
    ["Brand", "Freljord", "Runeterra"],
    ["Braum", "Freljord", ""],
    ["Briar", "Noxus", ""],
    ["Caitlyn", "Piltover", ""],
    ["Camille", "Piltover", ""],
    ["Cassiopeia", "Noxus", ""],
    ["Cho'Gath", "Void", ""],
    ["Corki", "Piltover", "Bandle City"],
    ["Darius", "Noxus", ""],
    ["Diana", "Targon", ""],
    ["Dr. Mundo", "Zaun", ""],
    ["Draven", "Noxus", ""],
    ["Ekko", "Zaun", ""],
    ["Elise", "Noxus", "Shadow Isles"],
    ["Evelynn", "Runeterra", ""],
    ["Ezreal", "Piltover", ""],
    ["Fiddlesticks", "Runeterra", ""],
    ["Fiora", "Demacia", ""],
    ["Fizz", "Bilgewater", "Bandle City"],
    ["Galio", "Demacia", ""],
    ["Gangplank", "Bilgewater", ""],
    ["Garen", "Demacia", ""],
    ["Gnar", "Freljord", "Bandle City"],
    ["Gragas", "Freljord", ""],
    ["Graves", "Bilgewater", ""],
    ["Gwen", "Shadow Isles", ""],
    ["Hecarim", "Shadow Isles", ""],
    ["Heimerdinger", "Piltover", "Bandle City"],
    ["Hwei", "Ionia", ""],
    ["Illaoi", "Bilgewater", ""],
    ["Irelia", "Ionia", ""],
    ["Ivern", "Ionia", "Freljord"],
    ["Janna", "Zaun", "Shurima"],
    ["Jarvan IV", "Demacia", ""],
    ["Jax", "Runeterra", "Shurima"],
    ["Jayce", "Piltover", ""],
    ["Jhin", "Ionia", ""],
    ["Jinx", "Zaun", ""],
    ["K'Sante", "Shurima", ""],
    ["Kai'Sa", "Void", "Shurima"],
    ["Kalista", "Shadow Isles", ""],
    ["Karma", "Ionia", ""],
    ["Karthus", "Shadow Isles", ""],
    ["Kassadin", "Void", "Shurima"],
    ["Katarina", "Noxus", ""],
    ["Kayle", "Demacia", "Targon"],
    ["Kayn", "Ionia", "Noxus"],
    ["Kennen", "Ionia", "Bandle City"],
    ["Kha'Zix", "Void", ""],
    ["Kindred", "Runeterra", ""],
    ["Kled", "Noxus", "Bandle City"],
    ["Kog'Maw", "Void", "Icathia"],
    ["LeBlanc", "Noxus", ""],
    ["Lee Sin", "Ionia", ""],
    ["Leona", "Targon", ""],
    ["Lillia", "Ionia", ""],
    ["Lissandra", "Freljord", ""],
    ["Lucian", "Demacia", "Shadow Isles"],
    ["Lulu", "Bandle City", ""],
    ["Lux", "Demacia", ""],
    ["Malphite", "Ionia", "Shurima"],
    ["Malzahar", "Void", "Shurima"],
    ["Maokai", "Shadow Isles", ""],
    ["Master Yi", "Ionia", ""],
    ["Milio", "Ixtal", ""],
    ["Miss Fortune", "Bilgewater", ""],
    ["Mordekaiser", "Noxus", ""],
    ["Morgana", "Demacia", "Targon"],
    ["Nami", "Bilgewater", "Targon"],
    ["Nasus", "Shurima", ""],
    ["Nautilus", "Bilgewater", ""],
    ["Neeko", "Ixtal", ""],
    ["Nidalee", "Ixtal", ""],
    ["Nilah", "Bilgewater", ""],
    ["Nocturne", "Runeterra", ""],
    ["Nunu & Willump", "Freljord", ""],
    ["Olaf", "Freljord", ""],
    ["Orianna", "Piltover", ""],
    ["Ornn", "Freljord", ""],
    ["Pantheon", "Targon", ""],
    ["Poppy", "Demacia", "Bandle City"],
    ["Pyke", "Bilgewater", ""],
    ["Qiyana", "Ixtal", ""],
    ["Quinn", "Demacia", ""],
    ["Rakan", "Ionia", ""],
    ["Rammus", "Shurima", ""],
    ["Rek'Sai", "Void", "Shurima"],
    ["Rell", "Noxus", ""],
    ["Renata Glasc", "Zaun", ""],
    ["Renekton", "Shurima", ""],
    ["Rengar", "Ixtal", ""],
    ["Riven", "Noxus", "Ionia"],
    ["Rumble", "Bandle City", ""],
    ["Ryze", "Runeterra", ""],
    ["Samira", "Noxus", "Shurima"],
    ["Sejuani", "Freljord", ""],
    ["Senna", "Shadow Isles", ""],
    ["Seraphine", "Piltover", "Zaun"],
    ["Sett", "Ionia", ""],
    ["Shaco", "Runeterra", ""],
    ["Shen", "Ionia", ""],
    ["Shyvana", "Demacia", ""],
    ["Singed", "Zaun", ""],
    ["Sion", "Noxus", ""],
    ["Sivir", "Shurima", ""],
    ["Skarner", "Ixtal", "Shurima"],
    ["Smolder", "Bandle City", ""],
    ["Sona", "Demacia", "Ionia"],
    ["Soraka", "Targon", ""],
    ["Swain", "Noxus", ""],
    ["Sylas", "Demacia", "Freljord"],
    ["Syndra", "Ionia", ""],
    ["Tahm Kench", "Runeterra", "Bilgewater"],
    ["Taliyah", "Shurima", ""],
    ["Talon", "Noxus", ""],
    ["Taric", "Targon", "Demacia"],
    ["Teemo", "Bandle City", ""],
    ["Thresh", "Shadow Isles", ""],
    ["Tristana", "Bandle City", ""],
    ["Trundle", "Freljord", ""],
    ["Tryndamere", "Freljord", ""],
    ["Twisted Fate", "Bilgewater", ""],
    ["Twitch", "Zaun", ""],
    ["Udyr", "Freljord", "Ionia"],
    ["Urgot", "Zaun", "Noxus"],
    ["Varus", "Ionia", "Runeterra"],
    ["Vayne", "Demacia", ""],
    ["Veigar", "Bandle City", "Runeterra"],
    ["Vel'Koz", "Void", ""],
    ["Vex", "Bandle City", "Shadow Isles"],
    ["Vi", "Piltover", ""],
    ["Viego", "Shadow Isles", ""],
    ["Viktor", "Zaun", ""],
    ["Vladimir", "Noxus", ""],
    ["Volibear", "Freljord", ""],
    ["Warwick", "Zaun", ""],
    ["Wukong", "Ionia", ""],
    ["Xayah", "Ionia", ""],
    ["Xerath", "Shurima", ""],
    ["Xin Zhao", "Demacia", "Ionia"],
    ["Yasuo", "Ionia", ""],
    ["Yone", "Ionia", ""],
    ["Yorick", "Shadow Isles", ""],
    ["Yuumi", "Bandle City", ""],
    ["Zac", "Zaun", ""],
    ["Zed", "Ionia", ""],
    ["Zeri", "Zaun", ""],
    ["Ziggs", "Zaun", "Bandle City"],
    ["Zilean", "Runeterra", "Shurima"],
    ["Zoe", "Targon", ""],
    ["Zyra", "Ixtal", ""]
  ];
}